### ISSUE TITLE
Center and make the video full screen

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/breaking-news#3]
Make the video cover the entire screen (Or atleast a major portion of it)

**Comment by ShreyaPanale** [comment]
I would like to do this

**Comment by kkumuda** [comment]
i want to do this

**Comment by abhishek-pes** [comment]
@srujandeshpande I would like to work on this

**Comment by srujandeshpande** [comment]
For this issue, everyone can go ahead
